### ISSUE TITLE
paridisp

### ISSUE THREAD

**Issue by FabioZTessitore** [IannuccilloAntonio/helloworld#2]
il : si mette attaccato, es:
```py
if n%2 == 0:
  print "..."
```

**Comment by FabioZTessitore** [comment]
Aggiusta questo sennò non controllo il resto

**Comment by IannuccilloAntonio** [comment]
Prof siete crudele :) . Dopo arrivo a casa e modifico!

**Comment by IannuccilloAntonio** [comment]
Prof quindi ad es.  a == 0 si deve scrivere così?

**Comment by FabioZTessitore** [comment]
Muahahaha

Il 4 feb 2017 8:43 PM, "Antonio Iannuccillo" <notifications@github.com> ha
scritto:
