### ISSUE TITLE
sec grado

### ISSUE THREAD

**Issue by FabioZTessitore** [IannuccilloAntonio/helloworld#5]
Aggiusta

**Comment by FabioZTessitore** [comment]
`x1` e `x2` ti aspettano

**Comment by IannuccilloAntonio** [comment]
Non riesco a capire l'errore

**Comment by FabioZTessitore** [comment]
Guarda bene

**Comment by IannuccilloAntonio** [comment]
Facendo così?
![immagine](https://cloud.githubusercontent.com/assets/22572099/22796608/49e8d502-eefb-11e6-9bc0-a1b4753857f2.png)

**Comment by FabioZTessitore** [comment]
Niente da fare. Ma insomma, ti perdi con un'espressione?

**Comment by IannuccilloAntonio** [comment]
Non mi dite che ci vuole la parentesi a (2.0*a)?

**Comment by FabioZTessitore** [comment]
Vabbé, Non te lo dico

**Comment by IannuccilloAntonio** [comment]
Controllate adesso, le ho provate tuttee
